variable "resource_group_name" {}
variable "virtual_network_name" {}
variable "subnet_name" {}
variable "nic_name" {}
variable "ip_configuration_name" {}
variable "Docker_vm_name" {}
variable "location" {}
variable "vm_size" {}
variable "image_publisher" {}
variable "os_disk_name" {}
variable "os_disk_caching" {}
variable "os_disk_create_option" {}
variable "os_disk_managed_disk_type" {}
variable "computer_name" {}
variable "admin_username" {}
variable "admin_password" {}
variable "azurerm_network_interface_name" {}
variable "azurerm_subnet_name" {}
